### ISSUE TITLE
DataTable bug

### ISSUE THREAD

**Issue by jisqaqov** [Motorbootslalom/ellis#2]
Hello. I have got exception like that after i added scrollable to my datatable.

ERROR TypeError: Cannot read property 'style' of undefined
    at DataTable.fixColumnWidths (datatable.js:1548)
    at DataTable.initResizableColumns (datatable.js:1440)
    at DataTable.ngAfterViewChecked (datatable.js:477)
    at callProviderLifecycles (core.es5.js:11185)
    at callElementProvidersLifecycles (core.es5.js:11157)
    at callLifecycleHooksChildrenFirst (core.es5.js:11141)
    at checkAndUpdateView (core.es5.js:12246)
    at callViewAction (core.es5.js:12603)
    at execComponentViewsAction (core.es5.js:12535)
    at checkAndUpdateView (core.es5.js:12244)

My datatable code is like below:

<p-dataTable [value]="detailList" selectionMode="single" [(selection)]="detail"
                     [paginator]="true" [rows]="10" [responsive]="true" sortField="id" sortOrder="-1" [resizableColumns]="true"
                     scrollable="true" scrollHeight="10em" frozenWidth="200px" unfrozenWidth="600px">
            <p-column frozen="true" field="sheetName" header="{{'SHEET_NAME' | translate}}"></p-column>
            <p-column frozen="true" field="accountNumber" header="{{'ACCOUNT_NUMBER' | translate}}"></p-column>
            <p-column frozen="true" field="accountName" header="{{'ACCOUNT_NAME' | translate}}"></p-column>
            <p-column frozen="true" field="curCode" header="{{'CUR_CODE' | translate}}"></p-column>
            <p-column frozen="true" field="summa" header="{{'SUMMA' | translate}}"></p-column>
            <p-column frozen="true" field="totalKzt" header="{{'TOTAL_KZT' | translate}}"></p-column>

            <p-column [hidden]="hiddenSum11220" field="sum11220" header="{{'SUM_11220' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum11420" field="sum11420" header="{{'SUM_11420' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum12220" field="sum12220" header="{{'SUM_12220' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum12420" field="sum12420" header="{{'SUM_12420' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum12710" field="sum12710" header="{{'SUM_12710' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum13220" field="sum13220" header="{{'SUM_13220' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum13420" field="sum13420" header="{{'SUM_13420' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum13440" field="sum13440" header="{{'SUM_13440' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum13630" field="sum13630" header="{{'SUM_13630' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum13950" field="sum13950" header="{{'SUM_13950' | translate}}"></p-column>
            <p-column [hidden]="hiddenSum34320" field="sum34320" header="{{'SUM_34320' | translate}}"></p-column>
        </p-dataTable>

**Comment by tuxlife** [comment]
@jisqaqov wrong project?
